### ISSUE TITLE
Error when trying to configure PolygonMode

### ISSUE THREAD

**Issue by eduardomecchia** [watergis/maplibre-gl-terradraw#77]
Hi, first of all thanks a lot for your work on this wrapper.
My problem is, I'm wrapping the creation of `MaplibreTerradrawControl` in a Function Component for use in a `react-map-gl` Map. It all works out perfectly, until I try to configure `modeOptions` for PolygonMode.
If I copy and paste the code from your demo website for SelectMode, everything works fine, but when I swap out the modeOptions object with this one, for example:

```
const modeOptions = {
    polygon: new TerraDrawPolygonMode({
      cursors: {
        start: 'crosshair',
        close: 'crosshair',
      }
    }),
  };
```

I get this error:

<img width="668" alt="image" src="https://github.com/user-attachments/assets/96604485-74f1-4ee6-864c-35f0b63b6cff">

Which is the same error I get if I only use `polygon` as a mode, without `render`. But I think that's actually fine, as `render` should be required if you're not using the `open` prop.
I don't understand if I'm doing something wrong or if it's a problem of the package? I feel like I'm doing everything by the book here.

**Comment by JinIgarashi** [comment]
@eduardomecchia I think I fixed the bug in this PR (https://github.com/watergis/maplibre-gl-terradraw/pull/74) when no render mode is set. I just tried your modeOptions, it looks working in my side. could you try it again with the latest version?

**Comment by eduardomecchia** [comment]
I installed 0.4.3 and unfortunately the problem is still there with the same error.
I think it's a separate issue from the one you linked because it occurs whenever I configure polygon mode, doesn't matter if I also have render or not.

```
const TERRA_DRAW_MODES = ['polygon'];
const TERRA_DRAW_MODES = ['render', 'polygon'];
```

These are the two mode arrays I'm feeding to my `TerraDrawControl`.

**Comment by JinIgarashi** [comment]
@eduardomecchia I realized m.state sometimes keep remained as registered state. Thus, in some timing, when the plugin is added to maplibre map object repeatedly, terradraw throw the error. I fixed in the below PR to force reset mode state to unregistered. could you try version 0.4.4?

https://github.com/watergis/maplibre-gl-terradraw/pull/86

**Comment by JinIgarashi** [comment]
@eduardomecchia cool! let me close this issue now. Please feel free to open issues if anything
